/* Generated by `npm run contracts` from docs/contracts/*.schema.json. Do not edit by hand:
 * change `bankagent.contracts.api`, run `uv run poe contracts`, then `npm run contracts`. */

export type Language = 'es' | 'pt'
export type ActionType = 'create_dispute' | 'block_card' | 'create_handoff'
export type Channel = 'ATM' | 'Branch' | 'Web' | 'App' | 'POS' | 'Transfer'
export type TransactionStatus = 'Approved' | 'Declined' | 'Pending' | 'Reversed'
export type TransactionType =
  'Deposit' | 'Withdrawal' | 'Transfer' | 'Payment' | 'Purchase' | 'Adjustment'

export interface ApiContracts {
  PersonaResponse: PersonaResponse
  LoginRequest: LoginRequest
  LoginResponse: LoginResponse
  VerifyRequest: VerifyRequest
  VerifyResponse: VerifyResponse
  SessionResponse: SessionResponse
  ChatTurnRequest: ChatTurnRequest
  ChatTurnResponse: ChatTurnResponse
  ConfirmationView: ConfirmationView
  TransactionView: TransactionView
}
/**
 * A demo persona: an opaque id (a keyed hash), never the customer id.
 */
export interface PersonaResponse {
  country: string
  first_name: string
  language: Language | null
  persona_id: string
}
export interface LoginRequest {
  /**
   * the code shared with the people invited to a public demo (DEMO_ACCESS_CODE, T15); a deployment that sets one refuses a login without it with 403 access_code_required
   */
  access_code?: string | null
  persona_id: string
}
export interface LoginResponse {
  challenge_id: string
  delivery?: string
  expires_at: string
  /**
   * the code itself, only with AUTH_EXPOSE_MOCK_OTP on synthetic data
   */
  mock_otp?: string | null
}
export interface VerifyRequest {
  challenge_id: string
  code: string
}
export interface VerifyResponse {
  expires_at: string
  first_name: string
  language: Language | null
  token: string
  token_type?: string
}
export interface SessionResponse {
  expires_at: string
  language: Language | null
}
export interface ChatTurnRequest {
  /**
   * preferred response language; omitted requests follow the customer's message
   */
  language?: Language | null
  text: string
}
/**
 * One agent reply.
 *
 * ``claimed_actions`` lists only writes verified by read-back. ``confirmation`` is set exactly
 * when the reply asks the customer to confirm a write; the customer answers in the chat ("Sí"
 * or "No"), and the token for the write is issued at that yes, server side. ``language`` is the
 * language the agent replied in, which follows the requested preference when provided, or the
 * customer's message otherwise.
 */
export interface ChatTurnResponse {
  claimed_actions: ActionType[]
  confirmation?: ConfirmationView | null
  ended: boolean
  language: Language
  reply_text: string
}
/**
 * The write a confirmation question asks about, as the question states it.
 *
 * Built from the same verified read as the question (``bankagent.render``), and the values are
 * the question's own display strings in the conversation's language: the UI labels them and
 * never formats or derives them, so the panel cannot show other facts than the question. A
 * dispute shows the reason and the charge (merchant, date, channel, amount, card ending); a
 * card block shows the card ending only.
 */
export interface ConfirmationView {
  action: ActionType
  amount?: string | null
  card_last4: string
  channel?: string | null
  date?: string | null
  merchant?: string | null
  reason?: string | null
}
/**
 * A transaction as the agent may see it. No fraud label or score by design (ADR 0003).
 */
export interface TransactionView {
  amount: number | string
  amount_usd?: number | string | null
  card_last4?: string | null
  channel: Channel
  currency: string
  is_foreign: boolean
  merchant_category?: string | null
  merchant_name?: string | null
  product_id: string
  transaction_category?: string | null
  transaction_city?: string | null
  transaction_country: string
  transaction_id: string
  transaction_status: TransactionStatus
  transaction_ts: string
  transaction_type: TransactionType
}

/** Length limits of the request fields, from the same schemas: inputs take maxLength here. */
export const LIMITS = {
  LoginRequest: {
    access_code: { minLength: 1, maxLength: 128 },
    persona_id: { minLength: 1, maxLength: 64 },
  },
  VerifyRequest: {
    challenge_id: { minLength: 1, maxLength: 64 },
    code: { minLength: 1, maxLength: 12 },
  },
  ChatTurnRequest: {
    text: { minLength: 1, maxLength: 2000 },
  },
} as const
