// Generate src/api/contracts.gen.ts from the API's JSON Schemas in docs/contracts/ (exported from
// `bankagent.contracts.api` by `uv run poe contracts`). The UI never redefines these shapes by hand
// (docs/rules/web.md).
//
//   node scripts/contracts.mjs          write src/api/contracts.gen.ts
//   node scripts/contracts.mjs --check  exit 1 if the committed file is stale
import { readFile, writeFile } from 'node:fs/promises'
import { compile } from 'json-schema-to-typescript'

const MODELS = [
  'PersonaResponse',
  'LoginRequest',
  'LoginResponse',
  'VerifyRequest',
  'VerifyResponse',
  'SessionResponse',
  'ChatTurnRequest',
  'ChatTurnResponse',
  'ConfirmationView',
]
const SCHEMAS = new URL('../../docs/contracts/', import.meta.url)
const OUT = new URL('../src/api/contracts.gen.ts', import.meta.url)
const BANNER = `/* Generated by \`npm run contracts\` from docs/contracts/*.schema.json. Do not edit by hand:
 * change \`bankagent.contracts.api\`, run \`uv run poe contracts\`, then \`npm run contracts\`. */`

// Property titles ("Reply Text") would each become a named alias; only model titles name types.
function dropPropertyTitles(schema) {
  for (const property of Object.values(schema.properties ?? {})) {
    delete property.title
    for (const option of property.anyOf ?? []) delete option.title
  }
  return schema
}

// One schema with every model and definition, so shared types (Language, ActionType) are
// declared once. Pydantic names a definition after its class, so equal names must be equal.
async function combinedSchema() {
  const defs = {}
  const add = (name, schema) => {
    if (name in defs && JSON.stringify(defs[name]) !== JSON.stringify(schema)) {
      throw new Error(`two different schemas are both named ${name}`)
    }
    defs[name] = schema
  }
  for (const name of MODELS) {
    const { $defs = {}, ...model } = JSON.parse(
      await readFile(new URL(`${name}.schema.json`, SCHEMAS), 'utf8'),
    )
    for (const [key, value] of Object.entries($defs)) add(key, dropPropertyTitles(value))
    add(name, dropPropertyTitles(model))
  }
  return {
    title: 'ApiContracts',
    type: 'object',
    additionalProperties: false,
    properties: Object.fromEntries(MODELS.map((name) => [name, { $ref: `#/$defs/${name}` }])),
    required: MODELS,
    $defs: defs,
  }
}

const generated = await compile(await combinedSchema(), 'ApiContracts', {
  bannerComment: BANNER,
  additionalProperties: false,
  style: { singleQuote: true, semi: false, printWidth: 100, trailingComma: 'all' },
})

if (process.argv.includes('--check')) {
  const current = await readFile(OUT, 'utf8').catch(() => '')
  if (current !== generated) {
    console.error('src/api/contracts.gen.ts is stale. Fix: npm run contracts, then commit it.')
    process.exit(1)
  }
  console.log(`API contracts up to date (${MODELS.length} models).`)
} else {
  await writeFile(OUT, generated)
  console.log(`Wrote src/api/contracts.gen.ts (${MODELS.length} models).`)
}
