"""Export the shared contracts as JSON Schema files under ``docs/contracts/``.

Usage:
    python -m bankagent.contracts.export          # regenerate docs/contracts/
    python -m bankagent.contracts.export --check  # exit 1 if docs/contracts/ is stale

Output is deterministic (sorted keys, LF, trailing newline) so the check is a plain text diff.
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path
from typing import Any

from pydantic import BaseModel

from bankagent.contracts import (
    api,
    comparison,
    console,
    decisions,
    domain,
    errors,
    evaluation,
    handoff,
    llm,
    records,
    tools,
)
from bankagent.contracts.serving import (
    FORBIDDEN_COLUMNS,
    REQUIRED_METADATA_KEYS,
    SERVING_CONTRACT_VERSION,
    SERVING_TABLES,
)

DEFAULT_OUT = Path(__file__).resolve().parents[3] / "docs" / "contracts"

EXPORTED_MODELS: tuple[type[BaseModel], ...] = (
    # domain
    domain.Session,
    domain.CardView,
    domain.TransactionView,
    domain.TransactionRiskSignals,
    domain.DisputeCase,
    domain.CardBlockEvent,
    domain.ConfirmationToken,
    # decisions
    decisions.DisputeSlots,
    decisions.InterpretationResult,
    decisions.RouterResult,
    decisions.PolicyDecision,
    # handoff
    handoff.HandoffDraft,
    handoff.HandoffPacket,
    # records
    records.ExecutionRecord,
    # evaluation
    evaluation.EvalCase,
    evaluation.EvalResult,
    comparison.ComparisonBundle,
    # tools
    tools.ToolContext,
    tools.ListCardsArgs,
    tools.ListCardsResult,
    tools.SearchTransactionsArgs,
    tools.SearchTransactionsResult,
    tools.GetTransactionArgs,
    tools.GetTransactionResult,
    tools.GetDisputeArgs,
    tools.GetDisputeResult,
    tools.CreateDisputeArgs,
    tools.CreateDisputeResult,
    tools.BlockCardArgs,
    tools.BlockCardResult,
    tools.CreateHandoffArgs,
    tools.CreateHandoffResult,
    errors.ToolErrorInfo,
    # llm
    llm.ChatMessage,
    llm.TokenUsage,
    # api (the web UI generates its types from these, `web/scripts/contracts.mjs`)
    api.PersonaResponse,
    api.LoginRequest,
    api.LoginResponse,
    api.VerifyRequest,
    api.VerifyResponse,
    api.SessionResponse,
    api.ChatTurnRequest,
    api.ChatTurnResponse,
    api.ConfirmationView,
    # console (human-agent console, T21; also web-generated)
    console.RuleExplanation,
    console.ConsoleHandoffEntry,
    console.ConsoleHandoffDetail,
    console.ConsoleDisputeEntry,
    console.ConsoleCardBlockEntry,
)


def _dump(data: Any) -> str:
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def render_all() -> dict[str, str]:
    """Return {relative file name: content} for every generated file."""
    files: dict[str, str] = {}
    for model in EXPORTED_MODELS:
        files[f"{model.__name__}.schema.json"] = _dump(model.model_json_schema(mode="validation"))

    files["serving_tables.json"] = _dump(
        {
            "contract_version": SERVING_CONTRACT_VERSION,
            "forbidden_columns": sorted(FORBIDDEN_COLUMNS),
            "required_metadata_keys": list(REQUIRED_METADATA_KEYS),
            "tables": [asdict(table) for table in SERVING_TABLES],
        }
    )

    lines = [
        "# Generated contracts",
        "",
        "Generated by `uv run poe contracts` from `src/bankagent/contracts/`.",
        "**Do not edit by hand**; CI fails (`poe contracts-check`) if these files are stale.",
        "",
        "JSON Schemas use Pydantic *validation* mode (what producers must send).",
        "",
        "| Schema | Module |",
        "|---|---|",
    ]
    for model in EXPORTED_MODELS:
        module = model.__module__.removeprefix("bankagent.contracts.")
        lines.append(f"| [`{model.__name__}`]({model.__name__}.schema.json) | `{module}` |")
    lines += [
        "",
        f"Serving DB contract v{SERVING_CONTRACT_VERSION}: "
        "[`serving_tables.json`](serving_tables.json).",
        "",
    ]
    files["README.md"] = "\n".join(lines)
    return files


def write_all(out_dir: Path) -> list[str]:
    out_dir.mkdir(parents=True, exist_ok=True)
    files = render_all()
    for name, content in files.items():
        (out_dir / name).write_text(content, encoding="utf-8", newline="\n")
    stale = [p.name for p in out_dir.iterdir() if p.is_file() and p.name not in files]
    for name in stale:
        (out_dir / name).unlink()
    return sorted(files)


def check_all(out_dir: Path) -> list[str]:
    """Return drift problems between the generated content and the files on disk."""
    problems: list[str] = []
    files = render_all()
    for name, content in files.items():
        path = out_dir / name
        if not path.exists():
            problems.append(f"missing: {name}")
        elif path.read_text(encoding="utf-8").replace("\r\n", "\n") != content:
            problems.append(f"stale: {name}")
    if out_dir.exists():
        for path in out_dir.iterdir():
            if path.is_file() and path.name not in files:
                problems.append(f"unexpected: {path.name}")
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Export shared contracts as JSON Schema.")
    parser.add_argument("--check", action="store_true", help="fail if docs/contracts is stale")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT)
    args = parser.parse_args(argv)

    if args.check:
        problems = check_all(args.out)
        if problems:
            print("docs/contracts is out of date:", file=sys.stderr)
            for problem in problems:
                print(f"  - {problem}", file=sys.stderr)
            print("Fix: uv run poe contracts, then commit docs/contracts/.", file=sys.stderr)
            return 1
        print(f"Contracts up to date ({len(render_all())} files).")
        return 0

    written = write_all(args.out)
    print(f"Wrote {len(written)} files to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
