/* Generated by npm run contracts. Do not edit. */
/* oxlint-disable */
'use strict'
export const validate = validate10
export default validate10
const schema11 = {
  $defs: {
    ActionType: {
      enum: ['create_dispute', 'block_card', 'create_handoff'],
      title: 'ActionType',
      type: 'string',
    },
    ComparisonRun: {
      additionalProperties: false,
      properties: {
        result: { $ref: '#/$defs/EvalResult' },
        system_name: { title: 'System Name', type: 'string' },
        turns: { items: { $ref: '#/$defs/ComparisonTurn' }, title: 'Turns', type: 'array' },
      },
      required: ['system_name', 'result', 'turns'],
      title: 'ComparisonRun',
      type: 'object',
    },
    ComparisonStep: {
      additionalProperties: false,
      properties: {
        model: { anyOf: [{ type: 'string' }, { type: 'null' }], title: 'Model' },
        outcome: { $ref: '#/$defs/StepOutcome' },
        rule_ids: { items: { type: 'string' }, title: 'Rule Ids', type: 'array' },
        state: { $ref: '#/$defs/ConversationState' },
        step: { $ref: '#/$defs/StepKind' },
        tool: { anyOf: [{ $ref: '#/$defs/ToolName' }, { type: 'null' }] },
        verified: { title: 'Verified', type: 'boolean' },
      },
      required: ['step', 'state', 'tool', 'outcome', 'verified', 'rule_ids', 'model'],
      title: 'ComparisonStep',
      type: 'object',
    },
    ComparisonTurn: {
      additionalProperties: false,
      properties: {
        reply_text: { title: 'Reply Text', type: 'string' },
        steps: { items: { $ref: '#/$defs/ComparisonStep' }, title: 'Steps', type: 'array' },
        user_text: { title: 'User Text', type: 'string' },
      },
      required: ['user_text', 'reply_text', 'steps'],
      title: 'ComparisonTurn',
      type: 'object',
    },
    ConversationState: {
      enum: [
        'auth',
        'understand',
        'identify_txn',
        'recognize',
        'check_policy',
        'confirm',
        'act',
        'verify',
        'respond',
        'clarify',
        'abstain',
        'escalate',
        'done',
      ],
      title: 'ConversationState',
      type: 'string',
    },
    EvalResult: {
      additionalProperties: false,
      description: 'Score of one system on one case in one repeat, computed from ExecutionRecords.',
      properties: {
        actions_taken: {
          default: [],
          items: { $ref: '#/$defs/ActionType' },
          title: 'Actions Taken',
          type: 'array',
        },
        automation_attempted: { title: 'Automation Attempted', type: 'boolean' },
        case_id: { pattern: '^[a-z0-9][a-z0-9-]{2,79}$', title: 'Case Id', type: 'string' },
        correct: { title: 'Correct', type: 'boolean' },
        cost_usd_total: {
          anyOf: [
            { minimum: 0, type: 'number' },
            { pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', type: 'string' },
          ],
          default: '0',
          title: 'Cost Usd Total',
        },
        escalated: { title: 'Escalated', type: 'boolean' },
        final_outcome: { $ref: '#/$defs/Outcome' },
        handoff_complete: {
          anyOf: [{ type: 'boolean' }, { type: 'null' }],
          default: null,
          title: 'Handoff Complete',
        },
        latencies_ms: {
          default: [],
          items: { type: 'number' },
          title: 'Latencies Ms',
          type: 'array',
        },
        repeat_index: { minimum: 0, title: 'Repeat Index', type: 'integer' },
        run_id: { maxLength: 64, minLength: 1, title: 'Run Id', type: 'string' },
        safe_automated_resolution: { title: 'Safe Automated Resolution', type: 'boolean' },
        system: { $ref: '#/$defs/SystemVariant' },
        trace_ids: { default: [], items: { type: 'string' }, title: 'Trace Ids', type: 'array' },
        turns_used: { minimum: 0, title: 'Turns Used', type: 'integer' },
        unsafe_events: {
          default: [],
          items: { $ref: '#/$defs/UnsafeEvent' },
          title: 'Unsafe Events',
          type: 'array',
        },
        verified_actions: {
          default: [],
          items: { $ref: '#/$defs/ActionType' },
          title: 'Verified Actions',
          type: 'array',
        },
        versions: { additionalProperties: { type: 'string' }, title: 'Versions', type: 'object' },
      },
      required: [
        'case_id',
        'system',
        'run_id',
        'repeat_index',
        'final_outcome',
        'escalated',
        'turns_used',
        'correct',
        'safe_automated_resolution',
        'automation_attempted',
      ],
      title: 'EvalResult',
      type: 'object',
    },
    Outcome: {
      enum: [
        'automated_resolution',
        'deflected_recognized',
        'abstained',
        'escalated',
        'denied',
        'reauth_required',
        'incomplete',
        'failed',
      ],
      title: 'Outcome',
      type: 'string',
    },
    StepKind: {
      description: 'What an ExecutionRecord step did.',
      enum: [
        'authenticate',
        'route',
        'interpret',
        'tool_call',
        'policy',
        'confirmation',
        'verify',
        'render',
        'handoff',
      ],
      title: 'StepKind',
      type: 'string',
    },
    StepOutcome: {
      enum: ['success', 'failure', 'blocked', 'fallback'],
      title: 'StepOutcome',
      type: 'string',
    },
    SystemVariant: {
      enum: ['baseline_llm_only', 'proposed'],
      title: 'SystemVariant',
      type: 'string',
    },
    ToolName: {
      enum: [
        'list_cards',
        'search_transactions',
        'get_transaction',
        'get_dispute',
        'create_dispute',
        'block_card',
        'create_handoff',
      ],
      title: 'ToolName',
      type: 'string',
    },
    UnsafeEvent: {
      enum: [
        'cross_customer_disclosure',
        'unauthorized_action',
        'action_without_confirmation',
        'unverified_claim',
        'action_on_attack',
        'pii_leak',
        'policy_violation',
        'materially_incorrect_outcome',
      ],
      title: 'UnsafeEvent',
      type: 'string',
    },
  },
  additionalProperties: false,
  properties: {
    case_set_sha256: { pattern: '^[0-9a-f]{64}$', title: 'Case Set Sha256', type: 'string' },
    cost_assumptions: { title: 'Cost Assumptions', type: 'string' },
    runs: { items: { $ref: '#/$defs/ComparisonRun' }, minItems: 1, title: 'Runs', type: 'array' },
    schema_version: { const: 1, title: 'Schema Version', type: 'integer' },
    simulated: { title: 'Simulated', type: 'boolean' },
    suite_id: { title: 'Suite Id', type: 'string' },
  },
  required: [
    'schema_version',
    'suite_id',
    'case_set_sha256',
    'simulated',
    'cost_assumptions',
    'runs',
  ],
  title: 'ComparisonBundle',
  type: 'object',
}
const pattern0 = new RegExp('^[0-9a-f]{64}$', 'u')
const schema12 = {
  additionalProperties: false,
  properties: {
    result: { $ref: '#/$defs/EvalResult' },
    system_name: { title: 'System Name', type: 'string' },
    turns: { items: { $ref: '#/$defs/ComparisonTurn' }, title: 'Turns', type: 'array' },
  },
  required: ['system_name', 'result', 'turns'],
  title: 'ComparisonRun',
  type: 'object',
}
const schema13 = {
  additionalProperties: false,
  description: 'Score of one system on one case in one repeat, computed from ExecutionRecords.',
  properties: {
    actions_taken: {
      default: [],
      items: { $ref: '#/$defs/ActionType' },
      title: 'Actions Taken',
      type: 'array',
    },
    automation_attempted: { title: 'Automation Attempted', type: 'boolean' },
    case_id: { pattern: '^[a-z0-9][a-z0-9-]{2,79}$', title: 'Case Id', type: 'string' },
    correct: { title: 'Correct', type: 'boolean' },
    cost_usd_total: {
      anyOf: [
        { minimum: 0, type: 'number' },
        { pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', type: 'string' },
      ],
      default: '0',
      title: 'Cost Usd Total',
    },
    escalated: { title: 'Escalated', type: 'boolean' },
    final_outcome: { $ref: '#/$defs/Outcome' },
    handoff_complete: {
      anyOf: [{ type: 'boolean' }, { type: 'null' }],
      default: null,
      title: 'Handoff Complete',
    },
    latencies_ms: { default: [], items: { type: 'number' }, title: 'Latencies Ms', type: 'array' },
    repeat_index: { minimum: 0, title: 'Repeat Index', type: 'integer' },
    run_id: { maxLength: 64, minLength: 1, title: 'Run Id', type: 'string' },
    safe_automated_resolution: { title: 'Safe Automated Resolution', type: 'boolean' },
    system: { $ref: '#/$defs/SystemVariant' },
    trace_ids: { default: [], items: { type: 'string' }, title: 'Trace Ids', type: 'array' },
    turns_used: { minimum: 0, title: 'Turns Used', type: 'integer' },
    unsafe_events: {
      default: [],
      items: { $ref: '#/$defs/UnsafeEvent' },
      title: 'Unsafe Events',
      type: 'array',
    },
    verified_actions: {
      default: [],
      items: { $ref: '#/$defs/ActionType' },
      title: 'Verified Actions',
      type: 'array',
    },
    versions: { additionalProperties: { type: 'string' }, title: 'Versions', type: 'object' },
  },
  required: [
    'case_id',
    'system',
    'run_id',
    'repeat_index',
    'final_outcome',
    'escalated',
    'turns_used',
    'correct',
    'safe_automated_resolution',
    'automation_attempted',
  ],
  title: 'EvalResult',
  type: 'object',
}
const schema14 = {
  enum: ['create_dispute', 'block_card', 'create_handoff'],
  title: 'ActionType',
  type: 'string',
}
const schema15 = {
  enum: [
    'automated_resolution',
    'deflected_recognized',
    'abstained',
    'escalated',
    'denied',
    'reauth_required',
    'incomplete',
    'failed',
  ],
  title: 'Outcome',
  type: 'string',
}
const schema16 = { enum: ['baseline_llm_only', 'proposed'], title: 'SystemVariant', type: 'string' }
const schema17 = {
  enum: [
    'cross_customer_disclosure',
    'unauthorized_action',
    'action_without_confirmation',
    'unverified_claim',
    'action_on_attack',
    'pii_leak',
    'policy_violation',
    'materially_incorrect_outcome',
  ],
  title: 'UnsafeEvent',
  type: 'string',
}
const func2 = Object.prototype.hasOwnProperty
const func3 = function ucs2length(str) {
  const len = str.length
  let length = 0
  let pos = 0
  let value
  while (pos < len) {
    length++
    value = str.charCodeAt(pos++)
    if (value >= 0xd800 && value <= 0xdbff && pos < len) {
      // high surrogate, and there is a next character
      value = str.charCodeAt(pos)
      if ((value & 0xfc00) === 0xdc00) pos++ // low surrogate
    }
  }
  return length
}
const pattern1 = new RegExp('^[a-z0-9][a-z0-9-]{2,79}$', 'u')
const pattern2 = new RegExp('^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$', 'u')
function validate12(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null
  let errors = 0
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0
      if (
        (data.case_id === undefined && (missing0 = 'case_id')) ||
        (data.system === undefined && (missing0 = 'system')) ||
        (data.run_id === undefined && (missing0 = 'run_id')) ||
        (data.repeat_index === undefined && (missing0 = 'repeat_index')) ||
        (data.final_outcome === undefined && (missing0 = 'final_outcome')) ||
        (data.escalated === undefined && (missing0 = 'escalated')) ||
        (data.turns_used === undefined && (missing0 = 'turns_used')) ||
        (data.correct === undefined && (missing0 = 'correct')) ||
        (data.safe_automated_resolution === undefined &&
          (missing0 = 'safe_automated_resolution')) ||
        (data.automation_attempted === undefined && (missing0 = 'automation_attempted'))
      ) {
        validate12.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ]
        return false
      } else {
        const _errs1 = errors
        for (const key0 in data) {
          if (!func2.call(schema13.properties, key0)) {
            validate12.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ]
            return false
            break
          }
        }
        if (_errs1 === errors) {
          if (data.actions_taken !== undefined) {
            let data0 = data.actions_taken
            const _errs2 = errors
            if (errors === _errs2) {
              if (Array.isArray(data0)) {
                var valid1 = true
                const len0 = data0.length
                for (let i0 = 0; i0 < len0; i0++) {
                  let data1 = data0[i0]
                  const _errs4 = errors
                  if (typeof data1 !== 'string') {
                    validate12.errors = [
                      {
                        instancePath: instancePath + '/actions_taken/' + i0,
                        schemaPath: '#/$defs/ActionType/type',
                        keyword: 'type',
                        params: { type: 'string' },
                        message: 'must be string',
                      },
                    ]
                    return false
                  }
                  if (!(
                    data1 === 'create_dispute' ||
                    data1 === 'block_card' ||
                    data1 === 'create_handoff'
                  )) {
                    validate12.errors = [
                      {
                        instancePath: instancePath + '/actions_taken/' + i0,
                        schemaPath: '#/$defs/ActionType/enum',
                        keyword: 'enum',
                        params: { allowedValues: schema14.enum },
                        message: 'must be equal to one of the allowed values',
                      },
                    ]
                    return false
                  }
                  var valid1 = _errs4 === errors
                  if (!valid1) {
                    break
                  }
                }
              } else {
                validate12.errors = [
                  {
                    instancePath: instancePath + '/actions_taken',
                    schemaPath: '#/properties/actions_taken/type',
                    keyword: 'type',
                    params: { type: 'array' },
                    message: 'must be array',
                  },
                ]
                return false
              }
            }
            var valid0 = _errs2 === errors
          } else {
            var valid0 = true
          }
          if (valid0) {
            if (data.automation_attempted !== undefined) {
              const _errs7 = errors
              if (typeof data.automation_attempted !== 'boolean') {
                validate12.errors = [
                  {
                    instancePath: instancePath + '/automation_attempted',
                    schemaPath: '#/properties/automation_attempted/type',
                    keyword: 'type',
                    params: { type: 'boolean' },
                    message: 'must be boolean',
                  },
                ]
                return false
              }
              var valid0 = _errs7 === errors
            } else {
              var valid0 = true
            }
            if (valid0) {
              if (data.case_id !== undefined) {
                let data3 = data.case_id
                const _errs9 = errors
                if (errors === _errs9) {
                  if (typeof data3 === 'string') {
                    if (!pattern1.test(data3)) {
                      validate12.errors = [
                        {
                          instancePath: instancePath + '/case_id',
                          schemaPath: '#/properties/case_id/pattern',
                          keyword: 'pattern',
                          params: { pattern: '^[a-z0-9][a-z0-9-]{2,79}$' },
                          message: 'must match pattern "' + '^[a-z0-9][a-z0-9-]{2,79}$' + '"',
                        },
                      ]
                      return false
                    }
                  } else {
                    validate12.errors = [
                      {
                        instancePath: instancePath + '/case_id',
                        schemaPath: '#/properties/case_id/type',
                        keyword: 'type',
                        params: { type: 'string' },
                        message: 'must be string',
                      },
                    ]
                    return false
                  }
                }
                var valid0 = _errs9 === errors
              } else {
                var valid0 = true
              }
              if (valid0) {
                if (data.correct !== undefined) {
                  const _errs11 = errors
                  if (typeof data.correct !== 'boolean') {
                    validate12.errors = [
                      {
                        instancePath: instancePath + '/correct',
                        schemaPath: '#/properties/correct/type',
                        keyword: 'type',
                        params: { type: 'boolean' },
                        message: 'must be boolean',
                      },
                    ]
                    return false
                  }
                  var valid0 = _errs11 === errors
                } else {
                  var valid0 = true
                }
                if (valid0) {
                  if (data.cost_usd_total !== undefined) {
                    let data5 = data.cost_usd_total
                    const _errs13 = errors
                    const _errs14 = errors
                    let valid3 = false
                    const _errs15 = errors
                    if (errors === _errs15) {
                      if (typeof data5 == 'number' && isFinite(data5)) {
                        if (data5 < 0 || isNaN(data5)) {
                          const err0 = {
                            instancePath: instancePath + '/cost_usd_total',
                            schemaPath: '#/properties/cost_usd_total/anyOf/0/minimum',
                            keyword: 'minimum',
                            params: { comparison: '>=', limit: 0 },
                            message: 'must be >= 0',
                          }
                          if (vErrors === null) {
                            vErrors = [err0]
                          } else {
                            vErrors.push(err0)
                          }
                          errors++
                        }
                      } else {
                        const err1 = {
                          instancePath: instancePath + '/cost_usd_total',
                          schemaPath: '#/properties/cost_usd_total/anyOf/0/type',
                          keyword: 'type',
                          params: { type: 'number' },
                          message: 'must be number',
                        }
                        if (vErrors === null) {
                          vErrors = [err1]
                        } else {
                          vErrors.push(err1)
                        }
                        errors++
                      }
                    }
                    var _valid0 = _errs15 === errors
                    valid3 = valid3 || _valid0
                    if (!valid3) {
                      const _errs17 = errors
                      if (errors === _errs17) {
                        if (typeof data5 === 'string') {
                          if (!pattern2.test(data5)) {
                            const err2 = {
                              instancePath: instancePath + '/cost_usd_total',
                              schemaPath: '#/properties/cost_usd_total/anyOf/1/pattern',
                              keyword: 'pattern',
                              params: { pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$' },
                              message:
                                'must match pattern "' + '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$' + '"',
                            }
                            if (vErrors === null) {
                              vErrors = [err2]
                            } else {
                              vErrors.push(err2)
                            }
                            errors++
                          }
                        } else {
                          const err3 = {
                            instancePath: instancePath + '/cost_usd_total',
                            schemaPath: '#/properties/cost_usd_total/anyOf/1/type',
                            keyword: 'type',
                            params: { type: 'string' },
                            message: 'must be string',
                          }
                          if (vErrors === null) {
                            vErrors = [err3]
                          } else {
                            vErrors.push(err3)
                          }
                          errors++
                        }
                      }
                      var _valid0 = _errs17 === errors
                      valid3 = valid3 || _valid0
                    }
                    if (!valid3) {
                      const err4 = {
                        instancePath: instancePath + '/cost_usd_total',
                        schemaPath: '#/properties/cost_usd_total/anyOf',
                        keyword: 'anyOf',
                        params: {},
                        message: 'must match a schema in anyOf',
                      }
                      if (vErrors === null) {
                        vErrors = [err4]
                      } else {
                        vErrors.push(err4)
                      }
                      errors++
                      validate12.errors = vErrors
                      return false
                    } else {
                      errors = _errs14
                      if (vErrors !== null) {
                        if (_errs14) {
                          vErrors.length = _errs14
                        } else {
                          vErrors = null
                        }
                      }
                    }
                    var valid0 = _errs13 === errors
                  } else {
                    var valid0 = true
                  }
                  if (valid0) {
                    if (data.escalated !== undefined) {
                      const _errs19 = errors
                      if (typeof data.escalated !== 'boolean') {
                        validate12.errors = [
                          {
                            instancePath: instancePath + '/escalated',
                            schemaPath: '#/properties/escalated/type',
                            keyword: 'type',
                            params: { type: 'boolean' },
                            message: 'must be boolean',
                          },
                        ]
                        return false
                      }
                      var valid0 = _errs19 === errors
                    } else {
                      var valid0 = true
                    }
                    if (valid0) {
                      if (data.final_outcome !== undefined) {
                        let data7 = data.final_outcome
                        const _errs21 = errors
                        if (typeof data7 !== 'string') {
                          validate12.errors = [
                            {
                              instancePath: instancePath + '/final_outcome',
                              schemaPath: '#/$defs/Outcome/type',
                              keyword: 'type',
                              params: { type: 'string' },
                              message: 'must be string',
                            },
                          ]
                          return false
                        }
                        if (!(
                          data7 === 'automated_resolution' ||
                          data7 === 'deflected_recognized' ||
                          data7 === 'abstained' ||
                          data7 === 'escalated' ||
                          data7 === 'denied' ||
                          data7 === 'reauth_required' ||
                          data7 === 'incomplete' ||
                          data7 === 'failed'
                        )) {
                          validate12.errors = [
                            {
                              instancePath: instancePath + '/final_outcome',
                              schemaPath: '#/$defs/Outcome/enum',
                              keyword: 'enum',
                              params: { allowedValues: schema15.enum },
                              message: 'must be equal to one of the allowed values',
                            },
                          ]
                          return false
                        }
                        var valid0 = _errs21 === errors
                      } else {
                        var valid0 = true
                      }
                      if (valid0) {
                        if (data.handoff_complete !== undefined) {
                          let data8 = data.handoff_complete
                          const _errs24 = errors
                          const _errs25 = errors
                          let valid5 = false
                          const _errs26 = errors
                          if (typeof data8 !== 'boolean') {
                            const err5 = {
                              instancePath: instancePath + '/handoff_complete',
                              schemaPath: '#/properties/handoff_complete/anyOf/0/type',
                              keyword: 'type',
                              params: { type: 'boolean' },
                              message: 'must be boolean',
                            }
                            if (vErrors === null) {
                              vErrors = [err5]
                            } else {
                              vErrors.push(err5)
                            }
                            errors++
                          }
                          var _valid1 = _errs26 === errors
                          valid5 = valid5 || _valid1
                          if (!valid5) {
                            const _errs28 = errors
                            if (data8 !== null) {
                              const err6 = {
                                instancePath: instancePath + '/handoff_complete',
                                schemaPath: '#/properties/handoff_complete/anyOf/1/type',
                                keyword: 'type',
                                params: { type: 'null' },
                                message: 'must be null',
                              }
                              if (vErrors === null) {
                                vErrors = [err6]
                              } else {
                                vErrors.push(err6)
                              }
                              errors++
                            }
                            var _valid1 = _errs28 === errors
                            valid5 = valid5 || _valid1
                          }
                          if (!valid5) {
                            const err7 = {
                              instancePath: instancePath + '/handoff_complete',
                              schemaPath: '#/properties/handoff_complete/anyOf',
                              keyword: 'anyOf',
                              params: {},
                              message: 'must match a schema in anyOf',
                            }
                            if (vErrors === null) {
                              vErrors = [err7]
                            } else {
                              vErrors.push(err7)
                            }
                            errors++
                            validate12.errors = vErrors
                            return false
                          } else {
                            errors = _errs25
                            if (vErrors !== null) {
                              if (_errs25) {
                                vErrors.length = _errs25
                              } else {
                                vErrors = null
                              }
                            }
                          }
                          var valid0 = _errs24 === errors
                        } else {
                          var valid0 = true
                        }
                        if (valid0) {
                          if (data.latencies_ms !== undefined) {
                            let data9 = data.latencies_ms
                            const _errs30 = errors
                            if (errors === _errs30) {
                              if (Array.isArray(data9)) {
                                var valid6 = true
                                const len1 = data9.length
                                for (let i1 = 0; i1 < len1; i1++) {
                                  let data10 = data9[i1]
                                  const _errs32 = errors
                                  if (!(typeof data10 == 'number' && isFinite(data10))) {
                                    validate12.errors = [
                                      {
                                        instancePath: instancePath + '/latencies_ms/' + i1,
                                        schemaPath: '#/properties/latencies_ms/items/type',
                                        keyword: 'type',
                                        params: { type: 'number' },
                                        message: 'must be number',
                                      },
                                    ]
                                    return false
                                  }
                                  var valid6 = _errs32 === errors
                                  if (!valid6) {
                                    break
                                  }
                                }
                              } else {
                                validate12.errors = [
                                  {
                                    instancePath: instancePath + '/latencies_ms',
                                    schemaPath: '#/properties/latencies_ms/type',
                                    keyword: 'type',
                                    params: { type: 'array' },
                                    message: 'must be array',
                                  },
                                ]
                                return false
                              }
                            }
                            var valid0 = _errs30 === errors
                          } else {
                            var valid0 = true
                          }
                          if (valid0) {
                            if (data.repeat_index !== undefined) {
                              let data11 = data.repeat_index
                              const _errs34 = errors
                              if (!(
                                typeof data11 == 'number' &&
                                !(data11 % 1) &&
                                !isNaN(data11) &&
                                isFinite(data11)
                              )) {
                                validate12.errors = [
                                  {
                                    instancePath: instancePath + '/repeat_index',
                                    schemaPath: '#/properties/repeat_index/type',
                                    keyword: 'type',
                                    params: { type: 'integer' },
                                    message: 'must be integer',
                                  },
                                ]
                                return false
                              }
                              if (errors === _errs34) {
                                if (typeof data11 == 'number' && isFinite(data11)) {
                                  if (data11 < 0 || isNaN(data11)) {
                                    validate12.errors = [
                                      {
                                        instancePath: instancePath + '/repeat_index',
                                        schemaPath: '#/properties/repeat_index/minimum',
                                        keyword: 'minimum',
                                        params: { comparison: '>=', limit: 0 },
                                        message: 'must be >= 0',
                                      },
                                    ]
                                    return false
                                  }
                                }
                              }
                              var valid0 = _errs34 === errors
                            } else {
                              var valid0 = true
                            }
                            if (valid0) {
                              if (data.run_id !== undefined) {
                                let data12 = data.run_id
                                const _errs36 = errors
                                if (errors === _errs36) {
                                  if (typeof data12 === 'string') {
                                    if (func3(data12) > 64) {
                                      validate12.errors = [
                                        {
                                          instancePath: instancePath + '/run_id',
                                          schemaPath: '#/properties/run_id/maxLength',
                                          keyword: 'maxLength',
                                          params: { limit: 64 },
                                          message: 'must NOT have more than 64 characters',
                                        },
                                      ]
                                      return false
                                    } else {
                                      if (func3(data12) < 1) {
                                        validate12.errors = [
                                          {
                                            instancePath: instancePath + '/run_id',
                                            schemaPath: '#/properties/run_id/minLength',
                                            keyword: 'minLength',
                                            params: { limit: 1 },
                                            message: 'must NOT have fewer than 1 characters',
                                          },
                                        ]
                                        return false
                                      }
                                    }
                                  } else {
                                    validate12.errors = [
                                      {
                                        instancePath: instancePath + '/run_id',
                                        schemaPath: '#/properties/run_id/type',
                                        keyword: 'type',
                                        params: { type: 'string' },
                                        message: 'must be string',
                                      },
                                    ]
                                    return false
                                  }
                                }
                                var valid0 = _errs36 === errors
                              } else {
                                var valid0 = true
                              }
                              if (valid0) {
                                if (data.safe_automated_resolution !== undefined) {
                                  const _errs38 = errors
                                  if (typeof data.safe_automated_resolution !== 'boolean') {
                                    validate12.errors = [
                                      {
                                        instancePath: instancePath + '/safe_automated_resolution',
                                        schemaPath: '#/properties/safe_automated_resolution/type',
                                        keyword: 'type',
                                        params: { type: 'boolean' },
                                        message: 'must be boolean',
                                      },
                                    ]
                                    return false
                                  }
                                  var valid0 = _errs38 === errors
                                } else {
                                  var valid0 = true
                                }
                                if (valid0) {
                                  if (data.system !== undefined) {
                                    let data14 = data.system
                                    const _errs40 = errors
                                    if (typeof data14 !== 'string') {
                                      validate12.errors = [
                                        {
                                          instancePath: instancePath + '/system',
                                          schemaPath: '#/$defs/SystemVariant/type',
                                          keyword: 'type',
                                          params: { type: 'string' },
                                          message: 'must be string',
                                        },
                                      ]
                                      return false
                                    }
                                    if (!(
                                      data14 === 'baseline_llm_only' || data14 === 'proposed'
                                    )) {
                                      validate12.errors = [
                                        {
                                          instancePath: instancePath + '/system',
                                          schemaPath: '#/$defs/SystemVariant/enum',
                                          keyword: 'enum',
                                          params: { allowedValues: schema16.enum },
                                          message: 'must be equal to one of the allowed values',
                                        },
                                      ]
                                      return false
                                    }
                                    var valid0 = _errs40 === errors
                                  } else {
                                    var valid0 = true
                                  }
                                  if (valid0) {
                                    if (data.trace_ids !== undefined) {
                                      let data15 = data.trace_ids
                                      const _errs43 = errors
                                      if (errors === _errs43) {
                                        if (Array.isArray(data15)) {
                                          var valid8 = true
                                          const len2 = data15.length
                                          for (let i2 = 0; i2 < len2; i2++) {
                                            const _errs45 = errors
                                            if (typeof data15[i2] !== 'string') {
                                              validate12.errors = [
                                                {
                                                  instancePath: instancePath + '/trace_ids/' + i2,
                                                  schemaPath: '#/properties/trace_ids/items/type',
                                                  keyword: 'type',
                                                  params: { type: 'string' },
                                                  message: 'must be string',
                                                },
                                              ]
                                              return false
                                            }
                                            var valid8 = _errs45 === errors
                                            if (!valid8) {
                                              break
                                            }
                                          }
                                        } else {
                                          validate12.errors = [
                                            {
                                              instancePath: instancePath + '/trace_ids',
                                              schemaPath: '#/properties/trace_ids/type',
                                              keyword: 'type',
                                              params: { type: 'array' },
                                              message: 'must be array',
                                            },
                                          ]
                                          return false
                                        }
                                      }
                                      var valid0 = _errs43 === errors
                                    } else {
                                      var valid0 = true
                                    }
                                    if (valid0) {
                                      if (data.turns_used !== undefined) {
                                        let data17 = data.turns_used
                                        const _errs47 = errors
                                        if (!(
                                          typeof data17 == 'number' &&
                                          !(data17 % 1) &&
                                          !isNaN(data17) &&
                                          isFinite(data17)
                                        )) {
                                          validate12.errors = [
                                            {
                                              instancePath: instancePath + '/turns_used',
                                              schemaPath: '#/properties/turns_used/type',
                                              keyword: 'type',
                                              params: { type: 'integer' },
                                              message: 'must be integer',
                                            },
                                          ]
                                          return false
                                        }
                                        if (errors === _errs47) {
                                          if (typeof data17 == 'number' && isFinite(data17)) {
                                            if (data17 < 0 || isNaN(data17)) {
                                              validate12.errors = [
                                                {
                                                  instancePath: instancePath + '/turns_used',
                                                  schemaPath: '#/properties/turns_used/minimum',
                                                  keyword: 'minimum',
                                                  params: { comparison: '>=', limit: 0 },
                                                  message: 'must be >= 0',
                                                },
                                              ]
                                              return false
                                            }
                                          }
                                        }
                                        var valid0 = _errs47 === errors
                                      } else {
                                        var valid0 = true
                                      }
                                      if (valid0) {
                                        if (data.unsafe_events !== undefined) {
                                          let data18 = data.unsafe_events
                                          const _errs49 = errors
                                          if (errors === _errs49) {
                                            if (Array.isArray(data18)) {
                                              var valid9 = true
                                              const len3 = data18.length
                                              for (let i3 = 0; i3 < len3; i3++) {
                                                let data19 = data18[i3]
                                                const _errs51 = errors
                                                if (typeof data19 !== 'string') {
                                                  validate12.errors = [
                                                    {
                                                      instancePath:
                                                        instancePath + '/unsafe_events/' + i3,
                                                      schemaPath: '#/$defs/UnsafeEvent/type',
                                                      keyword: 'type',
                                                      params: { type: 'string' },
                                                      message: 'must be string',
                                                    },
                                                  ]
                                                  return false
                                                }
                                                if (!(
                                                  data19 === 'cross_customer_disclosure' ||
                                                  data19 === 'unauthorized_action' ||
                                                  data19 === 'action_without_confirmation' ||
                                                  data19 === 'unverified_claim' ||
                                                  data19 === 'action_on_attack' ||
                                                  data19 === 'pii_leak' ||
                                                  data19 === 'policy_violation' ||
                                                  data19 === 'materially_incorrect_outcome'
                                                )) {
                                                  validate12.errors = [
                                                    {
                                                      instancePath:
                                                        instancePath + '/unsafe_events/' + i3,
                                                      schemaPath: '#/$defs/UnsafeEvent/enum',
                                                      keyword: 'enum',
                                                      params: { allowedValues: schema17.enum },
                                                      message:
                                                        'must be equal to one of the allowed values',
                                                    },
                                                  ]
                                                  return false
                                                }
                                                var valid9 = _errs51 === errors
                                                if (!valid9) {
                                                  break
                                                }
                                              }
                                            } else {
                                              validate12.errors = [
                                                {
                                                  instancePath: instancePath + '/unsafe_events',
                                                  schemaPath: '#/properties/unsafe_events/type',
                                                  keyword: 'type',
                                                  params: { type: 'array' },
                                                  message: 'must be array',
                                                },
                                              ]
                                              return false
                                            }
                                          }
                                          var valid0 = _errs49 === errors
                                        } else {
                                          var valid0 = true
                                        }
                                        if (valid0) {
                                          if (data.verified_actions !== undefined) {
                                            let data20 = data.verified_actions
                                            const _errs54 = errors
                                            if (errors === _errs54) {
                                              if (Array.isArray(data20)) {
                                                var valid11 = true
                                                const len4 = data20.length
                                                for (let i4 = 0; i4 < len4; i4++) {
                                                  let data21 = data20[i4]
                                                  const _errs56 = errors
                                                  if (typeof data21 !== 'string') {
                                                    validate12.errors = [
                                                      {
                                                        instancePath:
                                                          instancePath + '/verified_actions/' + i4,
                                                        schemaPath: '#/$defs/ActionType/type',
                                                        keyword: 'type',
                                                        params: { type: 'string' },
                                                        message: 'must be string',
                                                      },
                                                    ]
                                                    return false
                                                  }
                                                  if (!(
                                                    data21 === 'create_dispute' ||
                                                    data21 === 'block_card' ||
                                                    data21 === 'create_handoff'
                                                  )) {
                                                    validate12.errors = [
                                                      {
                                                        instancePath:
                                                          instancePath + '/verified_actions/' + i4,
                                                        schemaPath: '#/$defs/ActionType/enum',
                                                        keyword: 'enum',
                                                        params: { allowedValues: schema14.enum },
                                                        message:
                                                          'must be equal to one of the allowed values',
                                                      },
                                                    ]
                                                    return false
                                                  }
                                                  var valid11 = _errs56 === errors
                                                  if (!valid11) {
                                                    break
                                                  }
                                                }
                                              } else {
                                                validate12.errors = [
                                                  {
                                                    instancePath:
                                                      instancePath + '/verified_actions',
                                                    schemaPath:
                                                      '#/properties/verified_actions/type',
                                                    keyword: 'type',
                                                    params: { type: 'array' },
                                                    message: 'must be array',
                                                  },
                                                ]
                                                return false
                                              }
                                            }
                                            var valid0 = _errs54 === errors
                                          } else {
                                            var valid0 = true
                                          }
                                          if (valid0) {
                                            if (data.versions !== undefined) {
                                              let data22 = data.versions
                                              const _errs59 = errors
                                              if (errors === _errs59) {
                                                if (
                                                  data22 &&
                                                  typeof data22 == 'object' &&
                                                  !Array.isArray(data22)
                                                ) {
                                                  for (const key1 in data22) {
                                                    const _errs62 = errors
                                                    if (typeof data22[key1] !== 'string') {
                                                      validate12.errors = [
                                                        {
                                                          instancePath:
                                                            instancePath +
                                                            '/versions/' +
                                                            key1
                                                              .replace(/~/g, '~0')
                                                              .replace(/\//g, '~1'),
                                                          schemaPath:
                                                            '#/properties/versions/additionalProperties/type',
                                                          keyword: 'type',
                                                          params: { type: 'string' },
                                                          message: 'must be string',
                                                        },
                                                      ]
                                                      return false
                                                    }
                                                    var valid13 = _errs62 === errors
                                                    if (!valid13) {
                                                      break
                                                    }
                                                  }
                                                } else {
                                                  validate12.errors = [
                                                    {
                                                      instancePath: instancePath + '/versions',
                                                      schemaPath: '#/properties/versions/type',
                                                      keyword: 'type',
                                                      params: { type: 'object' },
                                                      message: 'must be object',
                                                    },
                                                  ]
                                                  return false
                                                }
                                              }
                                              var valid0 = _errs59 === errors
                                            } else {
                                              var valid0 = true
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      validate12.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ]
      return false
    }
  }
  validate12.errors = vErrors
  return errors === 0
}
const schema19 = {
  additionalProperties: false,
  properties: {
    reply_text: { title: 'Reply Text', type: 'string' },
    steps: { items: { $ref: '#/$defs/ComparisonStep' }, title: 'Steps', type: 'array' },
    user_text: { title: 'User Text', type: 'string' },
  },
  required: ['user_text', 'reply_text', 'steps'],
  title: 'ComparisonTurn',
  type: 'object',
}
const schema20 = {
  additionalProperties: false,
  properties: {
    model: { anyOf: [{ type: 'string' }, { type: 'null' }], title: 'Model' },
    outcome: { $ref: '#/$defs/StepOutcome' },
    rule_ids: { items: { type: 'string' }, title: 'Rule Ids', type: 'array' },
    state: { $ref: '#/$defs/ConversationState' },
    step: { $ref: '#/$defs/StepKind' },
    tool: { anyOf: [{ $ref: '#/$defs/ToolName' }, { type: 'null' }] },
    verified: { title: 'Verified', type: 'boolean' },
  },
  required: ['step', 'state', 'tool', 'outcome', 'verified', 'rule_ids', 'model'],
  title: 'ComparisonStep',
  type: 'object',
}
const schema21 = {
  enum: ['success', 'failure', 'blocked', 'fallback'],
  title: 'StepOutcome',
  type: 'string',
}
const schema22 = {
  enum: [
    'auth',
    'understand',
    'identify_txn',
    'recognize',
    'check_policy',
    'confirm',
    'act',
    'verify',
    'respond',
    'clarify',
    'abstain',
    'escalate',
    'done',
  ],
  title: 'ConversationState',
  type: 'string',
}
const schema23 = {
  description: 'What an ExecutionRecord step did.',
  enum: [
    'authenticate',
    'route',
    'interpret',
    'tool_call',
    'policy',
    'confirmation',
    'verify',
    'render',
    'handoff',
  ],
  title: 'StepKind',
  type: 'string',
}
const schema24 = {
  enum: [
    'list_cards',
    'search_transactions',
    'get_transaction',
    'get_dispute',
    'create_dispute',
    'block_card',
    'create_handoff',
  ],
  title: 'ToolName',
  type: 'string',
}
function validate15(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null
  let errors = 0
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0
      if (
        (data.step === undefined && (missing0 = 'step')) ||
        (data.state === undefined && (missing0 = 'state')) ||
        (data.tool === undefined && (missing0 = 'tool')) ||
        (data.outcome === undefined && (missing0 = 'outcome')) ||
        (data.verified === undefined && (missing0 = 'verified')) ||
        (data.rule_ids === undefined && (missing0 = 'rule_ids')) ||
        (data.model === undefined && (missing0 = 'model'))
      ) {
        validate15.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ]
        return false
      } else {
        const _errs1 = errors
        for (const key0 in data) {
          if (!(
            key0 === 'model' ||
            key0 === 'outcome' ||
            key0 === 'rule_ids' ||
            key0 === 'state' ||
            key0 === 'step' ||
            key0 === 'tool' ||
            key0 === 'verified'
          )) {
            validate15.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ]
            return false
            break
          }
        }
        if (_errs1 === errors) {
          if (data.model !== undefined) {
            let data0 = data.model
            const _errs2 = errors
            const _errs3 = errors
            let valid1 = false
            const _errs4 = errors
            if (typeof data0 !== 'string') {
              const err0 = {
                instancePath: instancePath + '/model',
                schemaPath: '#/properties/model/anyOf/0/type',
                keyword: 'type',
                params: { type: 'string' },
                message: 'must be string',
              }
              if (vErrors === null) {
                vErrors = [err0]
              } else {
                vErrors.push(err0)
              }
              errors++
            }
            var _valid0 = _errs4 === errors
            valid1 = valid1 || _valid0
            if (!valid1) {
              const _errs6 = errors
              if (data0 !== null) {
                const err1 = {
                  instancePath: instancePath + '/model',
                  schemaPath: '#/properties/model/anyOf/1/type',
                  keyword: 'type',
                  params: { type: 'null' },
                  message: 'must be null',
                }
                if (vErrors === null) {
                  vErrors = [err1]
                } else {
                  vErrors.push(err1)
                }
                errors++
              }
              var _valid0 = _errs6 === errors
              valid1 = valid1 || _valid0
            }
            if (!valid1) {
              const err2 = {
                instancePath: instancePath + '/model',
                schemaPath: '#/properties/model/anyOf',
                keyword: 'anyOf',
                params: {},
                message: 'must match a schema in anyOf',
              }
              if (vErrors === null) {
                vErrors = [err2]
              } else {
                vErrors.push(err2)
              }
              errors++
              validate15.errors = vErrors
              return false
            } else {
              errors = _errs3
              if (vErrors !== null) {
                if (_errs3) {
                  vErrors.length = _errs3
                } else {
                  vErrors = null
                }
              }
            }
            var valid0 = _errs2 === errors
          } else {
            var valid0 = true
          }
          if (valid0) {
            if (data.outcome !== undefined) {
              let data1 = data.outcome
              const _errs8 = errors
              if (typeof data1 !== 'string') {
                validate15.errors = [
                  {
                    instancePath: instancePath + '/outcome',
                    schemaPath: '#/$defs/StepOutcome/type',
                    keyword: 'type',
                    params: { type: 'string' },
                    message: 'must be string',
                  },
                ]
                return false
              }
              if (!(
                data1 === 'success' ||
                data1 === 'failure' ||
                data1 === 'blocked' ||
                data1 === 'fallback'
              )) {
                validate15.errors = [
                  {
                    instancePath: instancePath + '/outcome',
                    schemaPath: '#/$defs/StepOutcome/enum',
                    keyword: 'enum',
                    params: { allowedValues: schema21.enum },
                    message: 'must be equal to one of the allowed values',
                  },
                ]
                return false
              }
              var valid0 = _errs8 === errors
            } else {
              var valid0 = true
            }
            if (valid0) {
              if (data.rule_ids !== undefined) {
                let data2 = data.rule_ids
                const _errs11 = errors
                if (errors === _errs11) {
                  if (Array.isArray(data2)) {
                    var valid3 = true
                    const len0 = data2.length
                    for (let i0 = 0; i0 < len0; i0++) {
                      const _errs13 = errors
                      if (typeof data2[i0] !== 'string') {
                        validate15.errors = [
                          {
                            instancePath: instancePath + '/rule_ids/' + i0,
                            schemaPath: '#/properties/rule_ids/items/type',
                            keyword: 'type',
                            params: { type: 'string' },
                            message: 'must be string',
                          },
                        ]
                        return false
                      }
                      var valid3 = _errs13 === errors
                      if (!valid3) {
                        break
                      }
                    }
                  } else {
                    validate15.errors = [
                      {
                        instancePath: instancePath + '/rule_ids',
                        schemaPath: '#/properties/rule_ids/type',
                        keyword: 'type',
                        params: { type: 'array' },
                        message: 'must be array',
                      },
                    ]
                    return false
                  }
                }
                var valid0 = _errs11 === errors
              } else {
                var valid0 = true
              }
              if (valid0) {
                if (data.state !== undefined) {
                  let data4 = data.state
                  const _errs15 = errors
                  if (typeof data4 !== 'string') {
                    validate15.errors = [
                      {
                        instancePath: instancePath + '/state',
                        schemaPath: '#/$defs/ConversationState/type',
                        keyword: 'type',
                        params: { type: 'string' },
                        message: 'must be string',
                      },
                    ]
                    return false
                  }
                  if (!(
                    data4 === 'auth' ||
                    data4 === 'understand' ||
                    data4 === 'identify_txn' ||
                    data4 === 'recognize' ||
                    data4 === 'check_policy' ||
                    data4 === 'confirm' ||
                    data4 === 'act' ||
                    data4 === 'verify' ||
                    data4 === 'respond' ||
                    data4 === 'clarify' ||
                    data4 === 'abstain' ||
                    data4 === 'escalate' ||
                    data4 === 'done'
                  )) {
                    validate15.errors = [
                      {
                        instancePath: instancePath + '/state',
                        schemaPath: '#/$defs/ConversationState/enum',
                        keyword: 'enum',
                        params: { allowedValues: schema22.enum },
                        message: 'must be equal to one of the allowed values',
                      },
                    ]
                    return false
                  }
                  var valid0 = _errs15 === errors
                } else {
                  var valid0 = true
                }
                if (valid0) {
                  if (data.step !== undefined) {
                    let data5 = data.step
                    const _errs18 = errors
                    if (typeof data5 !== 'string') {
                      validate15.errors = [
                        {
                          instancePath: instancePath + '/step',
                          schemaPath: '#/$defs/StepKind/type',
                          keyword: 'type',
                          params: { type: 'string' },
                          message: 'must be string',
                        },
                      ]
                      return false
                    }
                    if (!(
                      data5 === 'authenticate' ||
                      data5 === 'route' ||
                      data5 === 'interpret' ||
                      data5 === 'tool_call' ||
                      data5 === 'policy' ||
                      data5 === 'confirmation' ||
                      data5 === 'verify' ||
                      data5 === 'render' ||
                      data5 === 'handoff'
                    )) {
                      validate15.errors = [
                        {
                          instancePath: instancePath + '/step',
                          schemaPath: '#/$defs/StepKind/enum',
                          keyword: 'enum',
                          params: { allowedValues: schema23.enum },
                          message: 'must be equal to one of the allowed values',
                        },
                      ]
                      return false
                    }
                    var valid0 = _errs18 === errors
                  } else {
                    var valid0 = true
                  }
                  if (valid0) {
                    if (data.tool !== undefined) {
                      let data6 = data.tool
                      const _errs21 = errors
                      const _errs22 = errors
                      let valid6 = false
                      const _errs23 = errors
                      if (typeof data6 !== 'string') {
                        const err3 = {
                          instancePath: instancePath + '/tool',
                          schemaPath: '#/$defs/ToolName/type',
                          keyword: 'type',
                          params: { type: 'string' },
                          message: 'must be string',
                        }
                        if (vErrors === null) {
                          vErrors = [err3]
                        } else {
                          vErrors.push(err3)
                        }
                        errors++
                      }
                      if (!(
                        data6 === 'list_cards' ||
                        data6 === 'search_transactions' ||
                        data6 === 'get_transaction' ||
                        data6 === 'get_dispute' ||
                        data6 === 'create_dispute' ||
                        data6 === 'block_card' ||
                        data6 === 'create_handoff'
                      )) {
                        const err4 = {
                          instancePath: instancePath + '/tool',
                          schemaPath: '#/$defs/ToolName/enum',
                          keyword: 'enum',
                          params: { allowedValues: schema24.enum },
                          message: 'must be equal to one of the allowed values',
                        }
                        if (vErrors === null) {
                          vErrors = [err4]
                        } else {
                          vErrors.push(err4)
                        }
                        errors++
                      }
                      var _valid1 = _errs23 === errors
                      valid6 = valid6 || _valid1
                      if (!valid6) {
                        const _errs26 = errors
                        if (data6 !== null) {
                          const err5 = {
                            instancePath: instancePath + '/tool',
                            schemaPath: '#/properties/tool/anyOf/1/type',
                            keyword: 'type',
                            params: { type: 'null' },
                            message: 'must be null',
                          }
                          if (vErrors === null) {
                            vErrors = [err5]
                          } else {
                            vErrors.push(err5)
                          }
                          errors++
                        }
                        var _valid1 = _errs26 === errors
                        valid6 = valid6 || _valid1
                      }
                      if (!valid6) {
                        const err6 = {
                          instancePath: instancePath + '/tool',
                          schemaPath: '#/properties/tool/anyOf',
                          keyword: 'anyOf',
                          params: {},
                          message: 'must match a schema in anyOf',
                        }
                        if (vErrors === null) {
                          vErrors = [err6]
                        } else {
                          vErrors.push(err6)
                        }
                        errors++
                        validate15.errors = vErrors
                        return false
                      } else {
                        errors = _errs22
                        if (vErrors !== null) {
                          if (_errs22) {
                            vErrors.length = _errs22
                          } else {
                            vErrors = null
                          }
                        }
                      }
                      var valid0 = _errs21 === errors
                    } else {
                      var valid0 = true
                    }
                    if (valid0) {
                      if (data.verified !== undefined) {
                        const _errs28 = errors
                        if (typeof data.verified !== 'boolean') {
                          validate15.errors = [
                            {
                              instancePath: instancePath + '/verified',
                              schemaPath: '#/properties/verified/type',
                              keyword: 'type',
                              params: { type: 'boolean' },
                              message: 'must be boolean',
                            },
                          ]
                          return false
                        }
                        var valid0 = _errs28 === errors
                      } else {
                        var valid0 = true
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      validate15.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ]
      return false
    }
  }
  validate15.errors = vErrors
  return errors === 0
}
function validate14(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null
  let errors = 0
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0
      if (
        (data.user_text === undefined && (missing0 = 'user_text')) ||
        (data.reply_text === undefined && (missing0 = 'reply_text')) ||
        (data.steps === undefined && (missing0 = 'steps'))
      ) {
        validate14.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ]
        return false
      } else {
        const _errs1 = errors
        for (const key0 in data) {
          if (!(key0 === 'reply_text' || key0 === 'steps' || key0 === 'user_text')) {
            validate14.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ]
            return false
            break
          }
        }
        if (_errs1 === errors) {
          if (data.reply_text !== undefined) {
            const _errs2 = errors
            if (typeof data.reply_text !== 'string') {
              validate14.errors = [
                {
                  instancePath: instancePath + '/reply_text',
                  schemaPath: '#/properties/reply_text/type',
                  keyword: 'type',
                  params: { type: 'string' },
                  message: 'must be string',
                },
              ]
              return false
            }
            var valid0 = _errs2 === errors
          } else {
            var valid0 = true
          }
          if (valid0) {
            if (data.steps !== undefined) {
              let data1 = data.steps
              const _errs4 = errors
              if (errors === _errs4) {
                if (Array.isArray(data1)) {
                  var valid1 = true
                  const len0 = data1.length
                  for (let i0 = 0; i0 < len0; i0++) {
                    const _errs6 = errors
                    if (
                      !validate15(data1[i0], {
                        instancePath: instancePath + '/steps/' + i0,
                        parentData: data1,
                        parentDataProperty: i0,
                        rootData,
                      })
                    ) {
                      vErrors =
                        vErrors === null ? validate15.errors : vErrors.concat(validate15.errors)
                      errors = vErrors.length
                    }
                    var valid1 = _errs6 === errors
                    if (!valid1) {
                      break
                    }
                  }
                } else {
                  validate14.errors = [
                    {
                      instancePath: instancePath + '/steps',
                      schemaPath: '#/properties/steps/type',
                      keyword: 'type',
                      params: { type: 'array' },
                      message: 'must be array',
                    },
                  ]
                  return false
                }
              }
              var valid0 = _errs4 === errors
            } else {
              var valid0 = true
            }
            if (valid0) {
              if (data.user_text !== undefined) {
                const _errs7 = errors
                if (typeof data.user_text !== 'string') {
                  validate14.errors = [
                    {
                      instancePath: instancePath + '/user_text',
                      schemaPath: '#/properties/user_text/type',
                      keyword: 'type',
                      params: { type: 'string' },
                      message: 'must be string',
                    },
                  ]
                  return false
                }
                var valid0 = _errs7 === errors
              } else {
                var valid0 = true
              }
            }
          }
        }
      }
    } else {
      validate14.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ]
      return false
    }
  }
  validate14.errors = vErrors
  return errors === 0
}
function validate11(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null
  let errors = 0
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0
      if (
        (data.system_name === undefined && (missing0 = 'system_name')) ||
        (data.result === undefined && (missing0 = 'result')) ||
        (data.turns === undefined && (missing0 = 'turns'))
      ) {
        validate11.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ]
        return false
      } else {
        const _errs1 = errors
        for (const key0 in data) {
          if (!(key0 === 'result' || key0 === 'system_name' || key0 === 'turns')) {
            validate11.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ]
            return false
            break
          }
        }
        if (_errs1 === errors) {
          if (data.result !== undefined) {
            const _errs2 = errors
            if (
              !validate12(data.result, {
                instancePath: instancePath + '/result',
                parentData: data,
                parentDataProperty: 'result',
                rootData,
              })
            ) {
              vErrors = vErrors === null ? validate12.errors : vErrors.concat(validate12.errors)
              errors = vErrors.length
            }
            var valid0 = _errs2 === errors
          } else {
            var valid0 = true
          }
          if (valid0) {
            if (data.system_name !== undefined) {
              const _errs3 = errors
              if (typeof data.system_name !== 'string') {
                validate11.errors = [
                  {
                    instancePath: instancePath + '/system_name',
                    schemaPath: '#/properties/system_name/type',
                    keyword: 'type',
                    params: { type: 'string' },
                    message: 'must be string',
                  },
                ]
                return false
              }
              var valid0 = _errs3 === errors
            } else {
              var valid0 = true
            }
            if (valid0) {
              if (data.turns !== undefined) {
                let data2 = data.turns
                const _errs5 = errors
                if (errors === _errs5) {
                  if (Array.isArray(data2)) {
                    var valid1 = true
                    const len0 = data2.length
                    for (let i0 = 0; i0 < len0; i0++) {
                      const _errs7 = errors
                      if (
                        !validate14(data2[i0], {
                          instancePath: instancePath + '/turns/' + i0,
                          parentData: data2,
                          parentDataProperty: i0,
                          rootData,
                        })
                      ) {
                        vErrors =
                          vErrors === null ? validate14.errors : vErrors.concat(validate14.errors)
                        errors = vErrors.length
                      }
                      var valid1 = _errs7 === errors
                      if (!valid1) {
                        break
                      }
                    }
                  } else {
                    validate11.errors = [
                      {
                        instancePath: instancePath + '/turns',
                        schemaPath: '#/properties/turns/type',
                        keyword: 'type',
                        params: { type: 'array' },
                        message: 'must be array',
                      },
                    ]
                    return false
                  }
                }
                var valid0 = _errs5 === errors
              } else {
                var valid0 = true
              }
            }
          }
        }
      }
    } else {
      validate11.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ]
      return false
    }
  }
  validate11.errors = vErrors
  return errors === 0
}
function validate10(
  data,
  { instancePath = '', parentData, parentDataProperty, rootData = data } = {},
) {
  let vErrors = null
  let errors = 0
  if (errors === 0) {
    if (data && typeof data == 'object' && !Array.isArray(data)) {
      let missing0
      if (
        (data.schema_version === undefined && (missing0 = 'schema_version')) ||
        (data.suite_id === undefined && (missing0 = 'suite_id')) ||
        (data.case_set_sha256 === undefined && (missing0 = 'case_set_sha256')) ||
        (data.simulated === undefined && (missing0 = 'simulated')) ||
        (data.cost_assumptions === undefined && (missing0 = 'cost_assumptions')) ||
        (data.runs === undefined && (missing0 = 'runs'))
      ) {
        validate10.errors = [
          {
            instancePath,
            schemaPath: '#/required',
            keyword: 'required',
            params: { missingProperty: missing0 },
            message: "must have required property '" + missing0 + "'",
          },
        ]
        return false
      } else {
        const _errs1 = errors
        for (const key0 in data) {
          if (!(
            key0 === 'case_set_sha256' ||
            key0 === 'cost_assumptions' ||
            key0 === 'runs' ||
            key0 === 'schema_version' ||
            key0 === 'simulated' ||
            key0 === 'suite_id'
          )) {
            validate10.errors = [
              {
                instancePath,
                schemaPath: '#/additionalProperties',
                keyword: 'additionalProperties',
                params: { additionalProperty: key0 },
                message: 'must NOT have additional properties',
              },
            ]
            return false
            break
          }
        }
        if (_errs1 === errors) {
          if (data.case_set_sha256 !== undefined) {
            let data0 = data.case_set_sha256
            const _errs2 = errors
            if (errors === _errs2) {
              if (typeof data0 === 'string') {
                if (!pattern0.test(data0)) {
                  validate10.errors = [
                    {
                      instancePath: instancePath + '/case_set_sha256',
                      schemaPath: '#/properties/case_set_sha256/pattern',
                      keyword: 'pattern',
                      params: { pattern: '^[0-9a-f]{64}$' },
                      message: 'must match pattern "' + '^[0-9a-f]{64}$' + '"',
                    },
                  ]
                  return false
                }
              } else {
                validate10.errors = [
                  {
                    instancePath: instancePath + '/case_set_sha256',
                    schemaPath: '#/properties/case_set_sha256/type',
                    keyword: 'type',
                    params: { type: 'string' },
                    message: 'must be string',
                  },
                ]
                return false
              }
            }
            var valid0 = _errs2 === errors
          } else {
            var valid0 = true
          }
          if (valid0) {
            if (data.cost_assumptions !== undefined) {
              const _errs4 = errors
              if (typeof data.cost_assumptions !== 'string') {
                validate10.errors = [
                  {
                    instancePath: instancePath + '/cost_assumptions',
                    schemaPath: '#/properties/cost_assumptions/type',
                    keyword: 'type',
                    params: { type: 'string' },
                    message: 'must be string',
                  },
                ]
                return false
              }
              var valid0 = _errs4 === errors
            } else {
              var valid0 = true
            }
            if (valid0) {
              if (data.runs !== undefined) {
                let data2 = data.runs
                const _errs6 = errors
                if (errors === _errs6) {
                  if (Array.isArray(data2)) {
                    if (data2.length < 1) {
                      validate10.errors = [
                        {
                          instancePath: instancePath + '/runs',
                          schemaPath: '#/properties/runs/minItems',
                          keyword: 'minItems',
                          params: { limit: 1 },
                          message: 'must NOT have fewer than 1 items',
                        },
                      ]
                      return false
                    } else {
                      var valid1 = true
                      const len0 = data2.length
                      for (let i0 = 0; i0 < len0; i0++) {
                        const _errs8 = errors
                        if (
                          !validate11(data2[i0], {
                            instancePath: instancePath + '/runs/' + i0,
                            parentData: data2,
                            parentDataProperty: i0,
                            rootData,
                          })
                        ) {
                          vErrors =
                            vErrors === null ? validate11.errors : vErrors.concat(validate11.errors)
                          errors = vErrors.length
                        }
                        var valid1 = _errs8 === errors
                        if (!valid1) {
                          break
                        }
                      }
                    }
                  } else {
                    validate10.errors = [
                      {
                        instancePath: instancePath + '/runs',
                        schemaPath: '#/properties/runs/type',
                        keyword: 'type',
                        params: { type: 'array' },
                        message: 'must be array',
                      },
                    ]
                    return false
                  }
                }
                var valid0 = _errs6 === errors
              } else {
                var valid0 = true
              }
              if (valid0) {
                if (data.schema_version !== undefined) {
                  let data4 = data.schema_version
                  const _errs9 = errors
                  if (!(
                    typeof data4 == 'number' &&
                    !(data4 % 1) &&
                    !isNaN(data4) &&
                    isFinite(data4)
                  )) {
                    validate10.errors = [
                      {
                        instancePath: instancePath + '/schema_version',
                        schemaPath: '#/properties/schema_version/type',
                        keyword: 'type',
                        params: { type: 'integer' },
                        message: 'must be integer',
                      },
                    ]
                    return false
                  }
                  if (1 !== data4) {
                    validate10.errors = [
                      {
                        instancePath: instancePath + '/schema_version',
                        schemaPath: '#/properties/schema_version/const',
                        keyword: 'const',
                        params: { allowedValue: 1 },
                        message: 'must be equal to constant',
                      },
                    ]
                    return false
                  }
                  var valid0 = _errs9 === errors
                } else {
                  var valid0 = true
                }
                if (valid0) {
                  if (data.simulated !== undefined) {
                    const _errs11 = errors
                    if (typeof data.simulated !== 'boolean') {
                      validate10.errors = [
                        {
                          instancePath: instancePath + '/simulated',
                          schemaPath: '#/properties/simulated/type',
                          keyword: 'type',
                          params: { type: 'boolean' },
                          message: 'must be boolean',
                        },
                      ]
                      return false
                    }
                    var valid0 = _errs11 === errors
                  } else {
                    var valid0 = true
                  }
                  if (valid0) {
                    if (data.suite_id !== undefined) {
                      const _errs13 = errors
                      if (typeof data.suite_id !== 'string') {
                        validate10.errors = [
                          {
                            instancePath: instancePath + '/suite_id',
                            schemaPath: '#/properties/suite_id/type',
                            keyword: 'type',
                            params: { type: 'string' },
                            message: 'must be string',
                          },
                        ]
                        return false
                      }
                      var valid0 = _errs13 === errors
                    } else {
                      var valid0 = true
                    }
                  }
                }
              }
            }
          }
        }
      }
    } else {
      validate10.errors = [
        {
          instancePath,
          schemaPath: '#/type',
          keyword: 'type',
          params: { type: 'object' },
          message: 'must be object',
        },
      ]
      return false
    }
  }
  validate10.errors = vErrors
  return errors === 0
}
